import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from '@aquabuilder/ui';
import AdminIndicator from './admin-indicator';
import HeaderAdminChip from './header-admin-chip';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="mx-auto max-w-6xl p-4 flex items-center gap-6">
            <Link href="/" className="font-semibold">AquaBuilder</Link>
            <nav className="text-sm text-gray-600 flex gap-4">
              <Link href="/build/new">Build</Link>
              <Link href="/browse">Browse</Link>
              <Link href="/community">Community</Link>
            </nav>
            <div className="ml-auto"><HeaderAdminChip /></div>
          </div>
        </header>
        <main>{children}</main>
        <AdminIndicator />
        <ToastContainer />
      </body>
    </html>
  );
}
import Link from 'next/link';
